version: 2.1
jobs: 
  build: 
    macos:  
      xcode: 11.3.0 # 選択された Xcode のバージョン
    steps: # 実行する一連のコマンド
      - checkout  # ユーザーのバージョン管理システムからコードをプル ダウンします
      - run: echo "hello world"
         
