version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: 
      name: win/default
      size: "medium"
      
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
        # - add_ssh_keys:
        #    fingerprints:
        #      - "2d:be:57:e7:a7:5a:53:24:b6:89:86:de:f2:13:cb:af"
        #- run: sh ./deploy.sh
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
