version: 2.1
  jobs:
    build-macos:
      macos:
        xcode: 11.3.0
          - image: circleci/node:4.8.2 # ジョブのコマンドが実行されるプライマリ コンテナ
      steps:
        - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
        - run: echo "hello world" # `echo` コマンドを実行します
