
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: 
      name: win/default
      # size: "medium"
      shell: powershell.exe
      
    # working_directory: ~/circleci-demo-python-django      
    steps:
      - checkout main# check out source code to working directory
      - run:            
         command: python -u test_BM1.py
         shell: powershell.exe
