
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
     executor: 
       name: win/default
       #working_directory: ~\OSS-project\task02
      # size: "medium"
       shell: powershell.exe
      
    # working_directory: ~/circleci-demo-python-django      
     steps:
       - checkout # check out source code to working directory
       - run:            
          command: python -u C:\Users\Xinjie\AppData\Local\Temp\MicrosoftEdgeDownloads\2a2117dc-5f3f-40e4-ba5e-b3bfb35f28ea\System-Development-Studio-main.zip\System-Development-Studio-main\test_BM1.py
          shell: powershell.exe
